#ifndef TOKEN_H
#define TOKEN_H

typedef enum {
    TOKEN_PROGRAM, TOKEN_VAR, TOKEN_INTEGER, TOKEN_REAL, TOKEN_CHAR,
    TOKEN_BEGIN, TOKEN_END, TOKEN_IF, TOKEN_THEN, TOKEN_ELSE,
    TOKEN_WHILE, TOKEN_DO, TOKEN_REPEAT, TOKEN_UNTIL, TOKEN_WRITE,
    TOKEN_DIV, TOKEN_AND, TOKEN_OR, TOKEN_NOT,
    TOKEN_IDENT, TOKEN_INTEIRO_LIT, TOKEN_REAL_LIT, TOKEN_CHAR_LIT,
    TOKEN_MAIS, TOKEN_MENOS, TOKEN_MULT, TOKEN_DIV_REAL,
    TOKEN_IGUAL, TOKEN_DIFERENTE, TOKEN_MENOR, TOKEN_MENOR_IGUAL,
    TOKEN_MAIOR, TOKEN_MAIOR_IGUAL, TOKEN_ATRIBUICAO,
    TOKEN_PONTO_VIRGULA, TOKEN_VIRGULA, TOKEN_DOIS_PONTOS, TOKEN_PONTO,
    TOKEN_ABRE_PAR, TOKEN_FECHA_PAR, TOKEN_EOF
} TokenType;

typedef struct {
    TokenType type;
    char lexeme[256];
} Token;

#endif